swagger: "2.0"
info:
  title: LMZ API
  version: 1.0.0
  contact:
    email: 1078649116@qq.com
basePath: /v1
paths:
  /api/:
    get:
      tags:
      - api
      description: GetAllArticle
      operationId: ArticleController.GetAll
      parameters:
      - in: body
        name: TagId
        description: your appid
        required: true
        schema:
          type: string
        type: string
      - in: body
        name: CatalogId
        description: your appid
        required: true
        schema:
          type: string
        type: string
      - in: body
        name: CreationTime
        description: your appid
        required: true
        schema:
          type: string
        type: string
      - in: body
        name: Filter
        description: your appid
        required: true
        schema:
          type: string
        type: string
      - in: body
        name: Sort
        description: your appid
        required: true
        schema:
          type: string
        type: string
      - in: body
        name: Order
        description: your appid
        required: true
        schema:
          type: string
        type: string
      - in: body
        name: SkipCount
        description: your appid
        required: true
        schema:
          type: string
        type: string
      - in: body
        name: MaxResultCount
        description: your appid
        required: true
        schema:
          type: string
        type: string
      responses:
        "200":
          description: Articles By Page
        "403":
          description: body is empty
